"use client";

import "./globals.css";

import { ApolloProvider } from "@apollo/client";
import { SessionProvider } from "next-auth/react";
import { ReduxProvider } from "@/utils/providers/redux";
import apolloClient from "@/utils/providers/apolloClient";
import TopNavbar from "@/components/navbar/TopNavbar";
import SideNavbar from "@/components/navbar/SideNavbar";

import DarkModeProvider from "@/utils/providers/darkModeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ReduxProvider>
            <ApolloProvider client={apolloClient}>
              <DarkModeProvider>
                <div className="min-h-screen flex flex-col items-center justify-center  dark:bg-black   dark:text-white relative">
                  <div className="absolute top-0">
                    <TopNavbar />
                  </div>
                  <div className="absolute left-0">
                    <SideNavbar />
                  </div>
                  {children}
                </div>
              </DarkModeProvider>
            </ApolloProvider>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
