"use client";

import "./globals.css";

import { ApolloProvider } from "@apollo/client";
import { SessionProvider } from "next-auth/react";
import apolloClient from "@/utils/providers/apolloClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ApolloProvider client={apolloClient}>{children}</ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
